#!/bin/bash

# Docker Obtenha a chave do repositório Docker
wget -O docker.gpg  https://download.docker.com/linux/debian/gpg 

# Adicionar a chave repo do Docker ao chaveiro do apt
gpg  --keyid-format 0xlong docker.gpg 2>/dev/null | grep -sq 0x8D81803C0EBFCD88 && sudo apt-key add docker.gpg

# Adicione o repositório Docker ao sources.list do apt
echo "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" | sudo tee /etc/apt/sources.list.d/docker.list

# Atualizar listas de pacotes:
sudo apt update

# Simule para verificar a instalação do docker
sudo apt --simulate install docker-ce

# Instalar docker
sudo apt install docker-ce
