#!/bin/bash

# Variaveis
USUARIO=$(git config user.name) # id do usuario / o mesmo do git
cd ~    # /home/user
DIRECTORY="Público"

# Verifica se o diretório não exite e cria-o
if [ ! -d "$DIRECTORY" ]; then
    mkdir $DIRECTORY
    echo "Diretório criado"
fi

cd $DIRECTORY

# Pega json que contem todos os repositorios e extrai as URLs (API do GitHub)
LIST_URL_CLONES=`curl --silent https://api.github.com/users/$USUARIO/repos -q | 
    grep "\"clone_url\"" |
    awk -F': "' '{print $2}' |
    sed -e 's/",//g'`

# Para cada url da lista faz um 'git clone'
for URL in $LIST_URL_CLONES; do
    echo "==>> clonando: " ${URL}
    git clone ${URL}
done
